"""added spikes subscriptions table

Revision ID: 20e3a00c640e
Revises: acdc8bb78ec6
Create Date: 2026-04-06 03:12:43.313958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e3a00c640e'
down_revision: Union[str, Sequence[str], None] = 'acdc8bb78ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spikes_subscriptions',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spikes_subscriptions')
    # ### end Alembic commands ###
