"""created subscriptions table

Revision ID: acdc8bb78ec6
Revises: 
Create Date: 2026-04-02 03:04:51.741953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acdc8bb78ec6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'service_id')
    )
    op.create_index('idx_service_id', 'subscriptions', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_service_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
